### ISSUE TITLE
Documentation small typos

### ISSUE THREAD

**Issue by dej611** [elastic/elasticsearch-py#2813]
I'll create a single issue to collect many small typos in the Python documentation:

* [`client.indeces`](https://elasticsearch-py.readthedocs.io/en/v8.17.1/api/indices.html) few instances of `~typing.Literal...` . Is that expected?
* On the (`delete_by_query`)[https://elasticsearch-py.readthedocs.io/en/v8.17.1/api/elasticsearch.html#elasticsearch.client.Elasticsearch.delete_by_query] page
  *  there's a `from_` argument with no documentation. Is it an alias for `from`? (Same on the `search` and few other APIs)
  * the `filter_path` has no documentation. (This can be found in other APIs of the same page)

**Comment by gioboa** [comment]
Hi 👋 is this issue still valid?

**Comment by gioboa** [comment]
Yep, that's the plan. I'll create a PR for this.

**Comment by gioboa** [comment]
> Yes, we should document from in the [delete_by_query` specification](https://github.com/elastic/elasticsearch-specification/blob/56f286b1398e8e83b68299dbe9ab2f92c1bcf130/specification/_global/delete_by_query/DeleteByQueryRequest.ts#L175). Are you asking because you would like to help! Pull requests are very welcome.

✅ Done. is it enough? do I need to change different repo too?

**Comment by pquentin** [comment]
Yes, that's enough, thank you!

I just realized that in 8.17.2 `from` has a description (https://elasticsearch-py.readthedocs.io/en/v8.17.1/api/elasticsearch.html#elasticsearch.client.Elasticsearch.delete_by_query), but we are still seeing `from_` and `from` incorrectly, which is https://github.com/elastic/elasticsearch-py/issues/2385 and I have to fix that myself.
