### ISSUE TITLE
RequestError: TransportError(400, u'mapper_parsing_exception', u'failed to parse')

### ISSUE THREAD

**Issue by abhigenie92** [elastic/elasticsearch-py#551]
Creating an index:

    def create_index(index_name):
        es=create_elastic_search_object()
        entry_mapping = {
        'entry-type': {
            'properties': {
                'text': {'type': 'string'},
                'coordinates': {'type': 'geo_point'},
                'username':{'type': 'string'} }
                }
                }
        es.indices.create(index_name,body={'mappings':entry_mapping})

Inserting into the index

    coordinates= str(tweet[0][0])+","+str(tweet[0][1])
    es.index(index=index_name, doc_type=keyword, id=start_id+ind, body={'text': tweet[1],'coordinates': coordinates,'username': tweet[2]})

Error:

    *** RequestError: TransportError(400, u'mapper_parsing_exception', u'failed to parse')

Debugging:

    (Pdb) body={'text': tweet[1],'coordinates': coordinates,'username': tweet[2]} 
    (Pdb) print body
    {'username': 'csd', 'text': 'RT @funder: Court Doc:Trump evicted a disabled US Veteran because he had a therapy dog\n\n@votevets #trumprussia #resist #theresistance #russ...', 'coordinates': '-117.1304909,32.7211149'}

All formats seem correct to me, what am I missing?

Libraries used:

    from elasticsearch import Elasticsearch

https://elasticsearch-py.readthedocs.io/en/master/

**Comment by HonzaKral** [comment]
You have a field in  your document that doesn't match your mappings. Inspect the `.info` attribute of the exception to get the whole information on which field it is.

**Comment by nbajason** [comment]
just got same error like you, looks like ES has some trouble when parse the dictionary, resolved by json.dumps(***).

**Comment by HonzaKral** [comment]
@nbajason what do you mean by "resolved by json.dumps"? The error has typically nothing to do with the document itself, instead referring to a field that failed to parse, so an individual value in your document doesn't match the type elasticsearch expects in its mappings - like trying to index a string as an integer...

**Comment by bicepjai** [comment]
how to ignore issues and insert other fields when non existing fields are there in the json data, when indexing ?

**Comment by HonzaKral** [comment]
You can set `dynamic` to `False` in the mappings and have elasticsearch ignore new fields. You can also set existing fields to be lenient and ignore malformed values by setting `ignore_malformed` to `True` - https://www.elastic.co/guide/en/elasticsearch/reference/6.1/ignore-malformed.html

**Comment by goolig** [comment]
The problem was solved for me by renaming the field '_id' to 'id'.

**Comment by apogre** [comment]
> You have a field in your document that doesn't match your mappings. Inspect the `.info` attribute of the exception to get the whole information on which field it is.

@HonzaKral I set the ignore_malformed to True but the issue persists. How can I locate the field that is giving the issue?

**Comment by HonzaKral** [comment]
@apogre You need to capture the exception instance and look at it's `.info`:

```python
try:
    # whatever causes the exception here
except TransportError as e:
    print(e.info)
```

**Comment by nishantgurunath** [comment]
Delete your ES index if you had uploaded some data previously with a different json/dict format.

**Comment by cs-sathwic** [comment]
use proper type during index creation. Try object
